server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA routing (React/Vite)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # favicon safety (prevents noise/errors)
    location = /favicon.ico {
        log_not_found off;
        access_log off;
        try_files $uri =404;
    }
}