apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: motherhood-app
type: Opaque
stringData:
  ACCESS_SECRET: "sdadkldhaslhdlasdlasdjal"
  REFRESH_SECRET: "lhdlasdhladlnldasdad"
  SIGNER_KEY: "dasdasfasfasfasfas"
  SECRET_KEY: "sdadkldhaslhdlasdlasdjal"
  DATABASE_PASSWORD: "npg_Hf5jvbVskE6U"