sonar.projectKey=motherhood-backend
sonar.projectName=Motherhood Backend

sonar.sources=.
sonar.language=py
sonar.python.version=3.11

sonar.exclusions=**/venv/**,**/__pycache__/**,**/alembic/**

sonar.host.url=http://localhost:9000
sonar.login=sqp_2df7c7ebce52dd83bae811c2c6096865d1c634ac
