apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: motherhood-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abidkarim74/SENIORYEARPROJECT_MOTHERHOODAPP
    targetRevision: development
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: motherhood-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true